import { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";
import { Users } from "../types";

const Home: NextPage<{ users: Users[] }> = ({ users }: any) => {
  console.log(users);

  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <h1 className="text-red-500">Yahallo!</h1>
      </div>
    </Layout>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  // const { data } = await axios.get("http://localhost:8080/api/users/")

  const res = await fetch(`http://localhost:8080/api/users/`);
  const data = await res.json();

  return {
    props: {
      users: data,
    },
  };
};

export default Home;
